### ISSUE TITLE
Failed to start Pgsql tools service 

### ISSUE THREAD

**Issue by alty-ir** [microsoft/azuredatastudio-postgresql#359]
Azure Data Studio Version: 1.43.0
OS: Windows 11 X64
```[tasklist]
### Tasks
- [ ] fix this soooon :)
```

**Comment by meldj** [comment]
Hi everyone,

**Failed to start Pgsql tools service**

I have the same error.

Azure Data Studio Version: 1.43.0
OS: Darwin arm64 22.4.0

Best regards

**Comment by realandrew** [comment]
I also have the same issue:

Azure Data Studio: 1.43.0
OS: Darwin arm64 22.4.0
PostreSQL Extension: 0.2.7

**Comment by amiru3f** [comment]
Hey ads guys ;-)
I also have same

**Comment by jhalmu** [comment]
Same issue here:

Azure Data Studio: 1.43.0
OS: Darwin arm64 22.4.0
PostreSQL Extension: 0.2.7

**Comment by matrs** [comment]
The previous release, `0.2.7` worked, but this update (`0.3.1`) fails. Also, there isn't any information logged. Previously I can  see some relevant information in `~/.config/azuredatastudio/logs/` , but now, there isn't anything related to this problem. 
I'm in `Linux  5.15.112`

**Comment by dwfallin** [comment]
also failing to 'start PGSQL tools service'!
ADS: 1.44.0
OS: Ubuntu 22.04
PostgreSQL: 0.3.1

**Comment by dwfallin** [comment]
so - was able to get 0.2.7 working - the ossdbtoolsservice_main was not executable, so chmod'd that and restarted ads and at least i'm talking to db's again!  it does not appear the 'service_main' file is even there in the 0.3.1 build? the out/ossdbtoolsservice/Linux/1.7.1/ folder is empty - not sure if it SHOULD be - but thats where i found the executable in the earlier release so maybe thats related?

**Comment by nasc17** [comment]
Issue has been addressed in our unstable release of PostgreSQL extension v0.4.0-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by meldj** [comment]
Hi,

I just tried it and now it works.

Version: 1.44.1
Commit: 8f53a316fa00a98264f1ab119641cd540b5af25c
Date: 2023-06-01T02:13:52.990Z (3 wks ago)
VS Code: 1.70.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.5.0

Name: PostgreSQL
Id: Microsoft.azuredatastudio-postgresql
Description: PostgreSQL extension for Azure Data Studio
Version: 0.3.1

Thank you so much!!

**Comment by hjrb** [comment]
> Issue has been addressed in our unstable release of PostgreSQL extension v0.4.0-insiders. We would appreciate your verification that it has been handled appropriately.

Still occurs with Azure Data Studio 
Version: 1.44.1 (system setup)
Commit: 8f53a316fa00a98264f1ab119641cd540b5af25c
Date: 2023-06-01T02:12:48.765Z
VS Code: 1.70.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045

and extension
v0.5.0

**Comment by hjrb** [comment]
Hi,
thank you for the continued effort.
1.) using the procedure to delete temp files and extension files and using the regular extension version does not work. A _MEI<6digit number> did not exist
2.) when I install the insider version I get a MS AppLocker warning preventing to use python310.dll
![Screenshot 2023-09-25 111937](https://github.com/microsoft/azuredatastudio-postgresql/assets/28059248/e019591b-3795-4acc-ad0f-d899c83840e4)
So that is a progress I guess.

**Comment by nasc17** [comment]
@hjrb thank you for the update. Please revert back to using the extension version that allows you to start the tools service. We are working on having a new release out in the next coming weeks.
