### ISSUE TITLE
PostgreSQL v0.3.1 breaks Linux support

### ISSUE THREAD

**Issue by karabaja4** [microsoft/azuredatastudio-postgresql#392]
Hello,

seems that an upgrade of PostgreSQL to v0.3.1 does not include Linux support:

![2023-05-30_22-12](https://github.com/microsoft/azuredatastudio-postgresql/assets/1043015/c8046b26-6572-445f-8027-54c826ed5c34)

Upon further investigation seems [config.json](https://github.com/microsoft/azuredatastudio-postgresql/blob/master/src/config.json) does not include pgtoolsservice Linux download definition at all, which is why service-downloader fails to download it.

Also pgtoolsservice v1.7.1 [releases page](https://github.com/microsoft/pgtoolsservice/releases/tag/v1.7.1) doesn't seem to include a Linux precompiled version which would be where the extension would look for it.

I successfully managed to compile my own pgtoolsservice for Linux and run it with the extension, but it's been a hassle.

Is this extension not packaged for Linux anymore?

**Comment by patrykwegrzyn** [comment]
im having the same issue

**Comment by alllballls** [comment]
same.

**Comment by GaryHopeMS** [comment]
The lack inclusion of Linux binaries as part of the v0.3.1 build was a miss, it will be addressed as part of the next release (M2).

**Comment by jasonweaver** [comment]
>  In the interim please download and install the v0.2.7 release from https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.2.7 using the instructions to install extension from VSX here https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/add-extensions?view=sql-server-ver16#install-from-a-vsix

In addition to manually installing the extension I had to also chmod [per this](https://github.com/microsoft/pgtoolsservice/issues/278#issuecomment-776796441).

**Comment by nasc17** [comment]
Issue has been addressed in our unstable release of PostgreSQL extension v0.4.0-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by karabaja4** [comment]
@nasc17 

Download still fails because service-downloader `downloadFileNames` object has "Linux_64" field and platform parameter (on Arch Linux) for me is "Ubuntu_16", which also seems to be default in `getRuntimeIdLinux` (I assume Arch is using an Ubuntu prebuilt).

However, if I cheat and modify serviceDownloadProvider this way:

```
L85    //const fileName = this.getDownloadFileName(platform);
L86    const installDirectory = this.getInstallDirectory(platform);
L87    const urlString = 'https://github.com/microsoft/pgtoolsservice/releases/download/1.8.0-insiders/pgsqltoolsservice-linux-x64-insiders.tar.gz'
```
The pgtoolsservice is downloaded but fails to start when the download is finished:
![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/1043015/dead8440-2d26-406a-a00a-6afb87fc224a)

However after a restart Postgres extension seems to work:
![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/1043015/acf1bb24-e99d-467d-b785-55f60412bce1)
![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/1043015/29b6d237-ecf9-40bc-a574-7ecc3bd24d5b)

**Comment by nasc17** [comment]
> @nasc17
> 
> Download still fails because service-downloader `downloadFileNames` object has "Linux_64" field and platform parameter (on Arch Linux) for me is "Ubuntu_16", which also seems to be default in `getRuntimeIdLinux` (I assume Arch is using an Ubuntu [prebuilt](https://aur.archlinux.org/packages/azuredatastudio-bin)).
> 
> However, if I cheat and modify serviceDownloadProvider.js this way:
> 
> ```
> L85    //const fileName = this.getDownloadFileName(platform);
> L86    const installDirectory = this.getInstallDirectory(platform);
> L87    const urlString = 'https://github.com/microsoft/pgtoolsservice/releases/download/1.8.0-insiders/pgsqltoolsservice-linux-x64-insiders.tar.gz';
> ```
> 
> The pgsqltoolsservice is downloaded but fails to start when the download is finished: ![image](https://user-images.githubusercontent.com/1043015/247995516-dead8440-2d26-406a-a00a-6afb87fc224a.png)
> 
> However after a restart Postgres extension seems to work: ![image](https://user-images.githubusercontent.com/1043015/247995910-acf1bb24-e99d-467d-b785-55f60412bce1.png) ![image](https://user-images.githubusercontent.com/1043015/247995800-29b6d237-ecf9-40bc-a574-7ecc3bd24d5b.png)

Thank you so much for quick feedback. We will keep you posted on updates. Stable version of extension will be released soon.

**Comment by karabaja4** [comment]
Hi @nasc17 

Trying to install v0.4.1 from the Extensions screen still fails with `Failed to start PGSQL tools service`, because `this._config` in `service-downloader` still does not include Ubuntu_16:
```json
{
    "executableFiles": [
        "pgsqltoolsservice/ossdbtoolsservice_main",
        "pgsqltoolsservice/ossdbtoolsservice_main.exe"
    ],
    "installDirectory": "/home/igor/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.4.1/out/ossdbtoolsservice/{#platform#}/{#version#}",
    "downloadFileNames": {
        "OSX_ARM64": "osx-arm64.tar.gz",
        "Windows_86": "win-x86.zip",
        "Windows_64": "win-x64.zip",
        "OSX": "osx.tar.gz",
        "Linux_64": "linux-x64.tar.gz"
    },
    "version": "v1.8.0",
    "downloadUrl": "https://github.com/Microsoft/pgtoolsservice/releases/download/{#version#}/pgsqltoolsservice-{#fileName#}",
    "proxy": "",
    "strictSSL": true
}
```

**Comment by nasc17** [comment]
> Hi @nasc17
> 
> Trying to install v0.4.1 from the Extensions screen still fails with `Failed to start PGSQL tools service`, because `this._config.downloadFileNames` in `node_modules/service-downloader/out/serviceDownloadProvider.js` still does not include `Ubuntu_16`:
> 
> **JSON.stringify(this._config)**
> 
> ```json
> {
>     "executableFiles": [
>         "pgsqltoolsservice/ossdbtoolsservice_main",
>         "pgsqltoolsservice/ossdbtoolsservice_main.exe"
>     ],
>     "installDirectory": "/home/igor/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.4.1/out/ossdbtoolsservice/{#platform#}/{#version#}",
>     "downloadFileNames": {
>         "OSX_ARM64": "osx-arm64.tar.gz",
>         "Windows_86": "win-x86.zip",
>         "Windows_64": "win-x64.zip",
>         "OSX": "osx.tar.gz",
>         "Linux_64": "linux-x64.tar.gz"
>     },
>     "version": "v1.8.0",
>     "downloadUrl": "https://github.com/Microsoft/pgtoolsservice/releases/download/{#version#}/pgsqltoolsservice-{#fileName#}",
>     "proxy": "",
>     "strictSSL": true
> }
> ```
> 
> P.S. Why is there a switch case for every distribution name/version, for example `node_modules/service-downloader/out/platform.js` in `getRuntimeIdLinux()`, if they all use the same binary (tarball) `linux-x64.tar.gz`? Couldn't all distributions just use the same runtime ID?

The config file has been updated in version 0.4.2 of the extension. We would appreciate if you could help to verify this has resolved your issue. Thank you.

**Comment by nasc17** [comment]
Hi @karabaja4 The config file has been updated in version 0.4.2 of the extension. We would appreciate if you could help to verify this has resolved your issue. Thank you.

**Comment by karabaja4** [comment]
Hi @nasc17 , yes it works now. Thanks for resolving this issue, I will close it now.
