### ISSUE TITLE
Failed to start Pgsql tools service on Linux

### ISSUE THREAD

**Issue by sigma-sappel** [microsoft/azuredatastudio-postgresql#395]
### System and application info: 
Version: 1.44.0
Commit: 31bee67f005648cdc9186f28ef39b4f1d6585e0f
Date: 2023-05-19T16:45:01.427Z
VS Code: 1.70.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.3.5-arch1-1
PostgresSQL extension: v0.3.1

When starting Azure Data Studio and installing PostgreSQL extension the startup of the extension fails.

**Failed to start PGSQL tools service**

I enabled debug logging and I see the following log entries:
`[2023-06-01 09:00:05.787] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.azuredatastudio-postgresql, startup: true, activationEvent: '*'
[2023-06-01 09:00:05.888] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
[2023-06-01 09:00:05.902] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2023-06-01 09:00:06.922] [exthost] [info] Eager extensions activated
[2023-06-01 09:00:06.927] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2023-06-01 09:01:13.946] [exthost] [info] Extension host terminating: received terminate message from renderer
[2023-06-01 09:01:13.954] [exthost] [error] An error occurred when deactivating the subscriptions for extension 'Microsoft.azuredatastudio-postgresql':
[2023-06-01 09:01:13.956] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'stop')
	at Object.dispose (/home/sappel/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.3.1/out/main.js:87:68)
	at g (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:12326)
	at w._deactivate (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:13293)
	at /opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:10618
	at Array.map (<anonymous>)
	at w._deactivateAll (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:10605)
	at w.terminate (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:10989)
	at w.terminate (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:620)
	at _ (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:19014)
	at /opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:16941
	at w.invoke (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:62:145)
	at D.deliver (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:62:2266)
	at b.fire (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:62:1844)
	at u.fire (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:18948)
	at n._receiveMessage (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:23535)
	at /opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:21069
	at w.invoke (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:62:145)
	at D.deliver (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:62:2266)
	at b.fire (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:62:1844)
	at b.acceptChunk (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:15779)
	at /opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:14909
	at Socket.d (/opt/azuredatastudio/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:26250)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[2023-06-01 09:01:13.957] [exthost] [info] Extension host with pid 32690 exiting with code 0`

**Comment by karabaja4** [comment]
Possible duplicate of #392

**Comment by GaryHopeMS** [comment]
The lack inclusion of Linux binaries as part of the v0.3.1 build was a miss, it will be addressed as part of the next release (M2).
See https://github.com/microsoft/azuredatastudio-postgresql/issues/397

**Comment by VeteraNovis** [comment]
> The lack inclusion of Linux binaries as part of the v0.3.1 build was a miss, it will be addressed as part of the next release (M2). See #397 In the interim please download and install the v0.2.7 release from https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.2.7 using the instructions to install extension from VSX here https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/add-extensions?view=sql-server-ver16#install-from-a-vsix

Upon following these instructions, I was also required to ensure this file was executable before everything worked. This is in Ubuntu 22.04

`
/home/USERNAME/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.2.7/out/ossdbtoolsservice/Linux/v1.5.0/pgsqltoolsservice/ossdbtoolsservice_main
`

**Comment by nasc17** [comment]
Issue has been addressed in our unstable release of PostgreSQL extension v0.4.0-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by matrs** [comment]
In version 0.4 1 still a problem. By the way , there is no file here:

```bash
 /home/mibu/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.4.1/out/ossdbtoolsservice/Linux/v1.8.0 
```

**Comment by nasc17** [comment]
Hi @matrs The config file has been updated in version 0.4.2 of the extension. We would appreciate if you could help to verify if this has resolved your issue. Thank you.

**Comment by matrs** [comment]
Now it works, thanks !
