### ISSUE TITLE
Connection Error after update to V0.4.1

### ISSUE THREAD

**Issue by mikebuchanon** [microsoft/azuredatastudio-postgresql#421]
Azure Data Studio automatically updated to v0.4.1 this morning when I tried to use it to run a query.

Now, all of my previously working connections give this error when I try to connect:

_dictionary update sequence element #3 has length 1; 2 is required_

I'm on Windows 10 and everything worked just fine on Friday 😄 I've tried recreating the connections and uninstalling and reinstalling the extension.   Doesn't seem to make a difference.

The developer console looks like this while it's failing:
![image](https://github.com/microsoft/azuredatastudio-postgresql/assets/1704017/5820b391-c9e5-4189-a939-9148d52c8fad)

workbench.desktop.main.js:893 sure seems to be doing a lot of work there 😄 

Any help would be greatly appreciated as I use this tool in quite a bit of my daily work 😄Thanks!

**Comment by nasc17** [comment]
We have published v0.4.2 in ADS Marketplace. Can you please verify if issue is present in new version. If so, for the time being you can download the previous version [here](https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.3.1).

**Comment by mikebuchanon** [comment]
Simply updating the extension to the newest version didn't resolve the existing issue.  However after the update I was able to recreate my connections and the recreated connections appear to work.   So, this may have helped, but folks with older saved connections might need to recreate them.  Thanks for the help and the quick turn around on the newer version!

**Comment by Skymogul** [comment]
Same issue even after completely uninstalling Data Studio and reinstalling, verifying 0.4.2 extension version, and removing and re-creating extensions. Used to work fine for me (and other on my team) as well and broke after update.

**Comment by nasc17** [comment]
@Skymogul can you please inform us the platform and pg version you are using.

**Comment by mariostrd** [comment]
Same error here as well. Tried recreating and reinstalling, but not working.

**Comment by DaeunYim** [comment]
I was unable to reproduce this error. I attempted an AAD connection to an Azure PostgreSQL server on both Windows 10 and 11, using ADS PG extensions 0.3 and 0.4, as well as ADS version 1.44 and previous versions. I did not encounter any errors.

There have been some new binaries introduced in the 0.4 version, and we suspect they may be related to the issue. Could you please follow the steps below to clean up your environment?

Navigate to "C:\Users<user_name>.azuredatastudio\extensions" and delete any existing PostgreSQL extensions. Don't worry about losing your connection information, as they will reappear once you reinstall the extension.

Open your file explorer and go to the "%temp%" location. Remove any folders named "_MEI<6digit number>" if they exist.

Once you have completed these steps, please try downloading and installing the new version of the PostgreSQL extension again.

Please let us know if this resolves the issue or if you need any further assistance.

**Comment by mikebuchanon** [comment]
@DaeunYim I'd cleaned all of that out and reinstalled the extension, but I hadn't removed the temp folders.   That didn't help, at least on the v.0.4.1 version.  

Ultimately what fixed it for me was simply creating new connection entries using the same details and removing the old connections.   So, AZ DS 1.44.1 with v0.4.2 of the PostgreSQL extension and it's working fine for me now.  

Thanks for your help!

**Comment by DaeunYim** [comment]
Thanks to @murlakatam, we identified the bug and incorporated the fix. We are planning to release the updated version by the end of this month.

**Comment by DaeunYim** [comment]
Closing after stable release

**Comment by nasc17** [comment]
Hello, issue has been addressed in our unstable release of PostgreSQL extension v0.4.3-insiders. We would appreciate your verification that it has been handled appropriately.

**Comment by murlakatam** [comment]
@nasc17 I can confirm I can connect using v0.4.3-insiders

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.5.0. Please reopen if issue is still present, thank you.
